##
##  Makefile -- Build procedure for sample hco Apache module
##  Autogenerated via ``apxs -n hco -g''.
##

builddir=.
top_srcdir=/Projects/Open/mapa/runtime
top_builddir=/Projects/Open/mapa/runtime
include /Projects/Open/mapa/runtime/build/special.mk

#   the used tools
APXS=/Projects/Open/mapa/runtime/bin/apxs
APACHECTL=/Projects/Open/mapa/runtime/bin/apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

INCLUDES+=-I/usr/local/include
LIBS=-L/usr/local/lib -lcurl
SH_LIBS=-lcurl

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_hco.o mod_hco.lo mod_hco.slo mod_hco.la 

#   simple test
test: reload
	lynx -mime_header http://localhost:8199/hco/index.html?app_id=myappid&app_key=myappkey

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

